/**
 * Book title mappings from book_title_map.yml
 * Maps display names, canonical-long, and canonical-short for Bible book recognition
 */

export const bookTitleMapData = [
  { display: 'THE BOOK OF GENESIS', 'canonical-long': 'Genesis', 'canonical-short': 'Gen' },
  { display: 'THE BOOK OF EXODUS', 'canonical-long': 'Exodus', 'canonical-short': 'Exod' },
  { display: 'THE BOOK OF LEVITICUS', 'canonical-long': 'Leviticus', 'canonical-short': 'Lev' },
  { display: 'THE BOOK OF NUMBERS', 'canonical-long': 'Numbers', 'canonical-short': 'Num' },
  { display: 'THE BOOK OF DEUTERONOMY', 'canonical-long': 'Deuteronomy', 'canonical-short': 'Deut' },
  { display: 'THE BOOK OF JOSUE', 'canonical-long': 'Joshua', 'canonical-short': 'Josh' },
  { display: 'THE BOOK OF JUDGES', 'canonical-long': 'Judges', 'canonical-short': 'Judg' },
  { display: 'THE BOOK OF RUTH', 'canonical-long': 'Ruth', 'canonical-short': 'Ruth' },
  { display: 'THE FIRST BOOK OF SAMUEL, OTHERWISE CALLED THE FIRST BOOK OF KINGS', 'canonical-long': '1 Samuel', 'canonical-short': '1 Sam' },
  { display: 'THE SECOND BOOK OF KINGS', 'canonical-long': '2 Samuel', 'canonical-short': '2 Sam' },
  { display: 'THE THIRD BOOK OF KINGS', 'canonical-long': '1 Kings', 'canonical-short': '1 Kgs' },
  { display: 'THE FOURTH BOOK OF KINGS', 'canonical-long': '2 Kings', 'canonical-short': '2 Kgs' },
  { display: 'THE FIRST BOOK OF PARALIPOMENON', 'canonical-long': '1 Chronicles', 'canonical-short': '1 Chr' },
  { display: 'THE SECOND BOOK OF PARALIPOMENON', 'canonical-long': '2 Chronicles', 'canonical-short': '2 Chr' },
  { display: 'THE FIRST BOOK OF ESDRAS', 'canonical-long': 'Ezra', 'canonical-short': 'Ezra' },
  { display: 'THE BOOK OF NEHEMIAS, WHICH IS CALLED THE SECOND OF ESDRAS', 'canonical-long': 'Nehemiah', 'canonical-short': 'Neh' },
  { display: 'THE BOOK OF JUDITH', 'canonical-long': 'Judith', 'canonical-short': 'Jdt' },
  { display: 'THE BOOK OF ESTHER', 'canonical-long': 'Esther', 'canonical-short': 'Esth' },
  { display: 'THE BOOK OF JOB', 'canonical-long': 'Job', 'canonical-short': 'Job' },
  { display: 'THE BOOK OF PSALMS', 'canonical-long': 'Psalms', 'canonical-short': 'Ps' },
  { display: 'THE BOOK OF PROVERBS', 'canonical-long': 'Proverbs', 'canonical-short': 'Prov' },
  { display: 'ECCLESIASTES', 'canonical-long': 'Ecclesiastes', 'canonical-short': 'Eccl' },
  { display: "SOLOMON'S CANTICLE OF CANTICLES", 'canonical-long': 'Song of Solomon', 'canonical-short': 'Song' },
  { display: 'THE BOOK OF WISDOM', 'canonical-long': 'Wisdom', 'canonical-short': 'Wis' },
  { display: 'ECCLESIASTICUS', 'canonical-long': 'Sirach', 'canonical-short': 'Sir' },
  { display: 'THE PROPHECY OF ISAIAS', 'canonical-long': 'Isaiah', 'canonical-short': 'Isa' },
  { display: 'THE PROPHECY OF JEREMIAS', 'canonical-long': 'Jeremiah', 'canonical-short': 'Jer' },
  { display: 'THE LAMENTATIONS OF JEREMIAS', 'canonical-long': 'Lamentations', 'canonical-short': 'Lam' },
  { display: 'THE PROPHECY OF BARUCH', 'canonical-long': 'Baruch', 'canonical-short': 'Bar' },
  { display: 'THE PROPHECY OF EZECHIEL', 'canonical-long': 'Ezekiel', 'canonical-short': 'Ezek' },
  { display: 'THE PROPHECY OF DANIEL', 'canonical-long': 'Daniel', 'canonical-short': 'Dan' },
  { display: 'THE PROPHECY OF OSEE', 'canonical-long': 'Hosea', 'canonical-short': 'Hos' },
  { display: 'THE PROPHECY OF JOEL', 'canonical-long': 'Joel', 'canonical-short': 'Joel' },
  { display: 'THE PROPHECY OF AMOS', 'canonical-long': 'Amos', 'canonical-short': 'Amos' },
  { display: 'THE PROPHECY OF ABDIAS', 'canonical-long': 'Obadiah', 'canonical-short': 'Obad' },
  { display: 'THE PROPHECY OF JONAS', 'canonical-long': 'Jonah', 'canonical-short': 'Jonah' },
  { display: 'THE PROPHECY OF MICHEAS', 'canonical-long': 'Micah', 'canonical-short': 'Mic' },
  { display: 'THE PROPHECY OF NAHUM', 'canonical-long': 'Nahum', 'canonical-short': 'Nah' },
  { display: 'THE PROPHECY OF HABACUC', 'canonical-long': 'Habakkuk', 'canonical-short': 'Hab' },
  { display: 'THE PROPHECY OF SOPHONIAS', 'canonical-long': 'Zephaniah', 'canonical-short': 'Zeph' },
  { display: 'THE PROPHECY OF AGGEUS', 'canonical-long': 'Haggai', 'canonical-short': 'Hag' },
  { display: 'THE PROPHECY OF ZACHARIAS', 'canonical-long': 'Zechariah', 'canonical-short': 'Zech' },
  { display: 'THE PROPHECY OF MALACHIAS', 'canonical-long': 'Malachi', 'canonical-short': 'Mal' },
  { display: 'THE FIRST BOOK OF MACHABEES', 'canonical-long': '1 Maccabees', 'canonical-short': '1 Macc' },
  { display: 'THE SECOND BOOK OF MACHABEES', 'canonical-long': '2 Maccabees', 'canonical-short': '2 Macc' },
  { display: 'THE HOLY GOSPEL OF JESUS CHRIST ACCORDING TO SAINT MATTHEW', 'canonical-long': 'Matthew', 'canonical-short': 'Matt' },
  { display: 'THE HOLY GOSPEL OF JESUS CHRIST ACCORDING TO ST. MARK', 'canonical-long': 'Mark', 'canonical-short': 'Mark' },
  { display: 'THE HOLY GOSPEL OF JESUS CHRIST ACCORDING TO ST. LUKE', 'canonical-long': 'Luke', 'canonical-short': 'Luke' },
  { display: 'THE HOLY GOSPEL OF JESUS CHRIST ACCORDING TO ST. JOHN', 'canonical-long': 'John', 'canonical-short': 'John' },
  { display: 'THE ACTS OF THE APOSTLES', 'canonical-long': 'Acts', 'canonical-short': 'Acts' },
  { display: 'THE EPISTLE OF ST. PAUL THE APOSTLE TO THE ROMANS', 'canonical-long': 'Romans', 'canonical-short': 'Rom' },
  { display: 'THE FIRST EPISTLE OF ST. PAUL TO THE CORINTHIANS', 'canonical-long': '1 Corinthians', 'canonical-short': '1 Cor' },
  { display: 'THE SECOND EPISTLE OF ST. PAUL TO THE CORINTHIANS', 'canonical-long': '2 Corinthians', 'canonical-short': '2 Cor' },
  { display: 'THE EPISTLE OF ST. PAUL TO THE GALATIANS', 'canonical-long': 'Galatians', 'canonical-short': 'Gal' },
  { display: 'THE EPISTLE OF ST. PAUL TO THE EPHESIANS', 'canonical-long': 'Ephesians', 'canonical-short': 'Eph' },
  { display: 'THE EPISTLE OF ST. PAUL TO THE PHILIPPIANS', 'canonical-long': 'Philippians', 'canonical-short': 'Phil' },
  { display: 'THE EPISTLE OF ST. PAUL TO THE COLOSSIANS', 'canonical-long': 'Colossians', 'canonical-short': 'Col' },
  { display: 'THE FIRST EPISTLE OF ST. PAUL TO THE THESSALONIANS', 'canonical-long': '1 Thessalonians', 'canonical-short': '1 Thess' },
  { display: 'THE SECOND EPISTLE OF ST. PAUL TO THE THESSALONIANS', 'canonical-long': '2 Thessalonians', 'canonical-short': '2 Thess' },
  { display: 'THE FIRST EPISTLE OF ST. PAUL TO TIMOTHY', 'canonical-long': '1 Timothy', 'canonical-short': '1 Tim' },
  { display: 'THE SECOND EPISTLE OF ST. PAUL TO TIMOTHY', 'canonical-long': '2 Timothy', 'canonical-short': '2 Tim' },
  { display: 'THE EPISTLE OF ST. PAUL TO TITUS', 'canonical-long': 'Titus', 'canonical-short': 'Titus' },
  { display: 'THE EPISTLE OF ST. PAUL TO PHILEMON', 'canonical-long': 'Philemon', 'canonical-short': 'Phlm' },
  { display: 'THE EPISTLE OF ST. PAUL TO THE HEBREWS', 'canonical-long': 'Hebrews', 'canonical-short': 'Heb' },
  { display: 'THE CATHOLIC EPISTLE OF ST. JAMES THE APOSTLE', 'canonical-long': 'James', 'canonical-short': 'Jas' },
  { display: 'THE FIRST EPISTLE OF ST. PETER THE APOSTLE', 'canonical-long': '1 Peter', 'canonical-short': '1 Pet' },
  { display: 'THE SECOND EPISTLE OF ST. PETER THE APOSTLE', 'canonical-long': '2 Peter', 'canonical-short': '2 Pet' },
  { display: 'THE FIRST EPISTLE OF ST. JOHN THE APOSTLE', 'canonical-long': '1 John', 'canonical-short': '1 John' },
  { display: 'THE SECOND EPISTLE OF ST. JOHN THE APOSTLE', 'canonical-long': '2 John', 'canonical-short': '2 John' },
  { display: 'THE THIRD EPISTLE OF ST. JOHN THE APOSTLE', 'canonical-long': '3 John', 'canonical-short': '3 John' },
  { display: 'THE CATHOLIC EPISTLE OF ST. JUDE', 'canonical-long': 'Jude', 'canonical-short': 'Jude' },
  { display: 'THE APOCALYPSE OF ST. JOHN THE APOSTLE', 'canonical-long': 'Revelation', 'canonical-short': 'Rev' }
];

