<script lang="ts">
  import type { BookReference } from '$lib/books';
  import { BOOK_TYPES } from '$lib/books';

  interface Props {
    query: string;
    bookType: string;
    parsedQuery: { references: BookReference[]; version?: string; versions?: string[] } | null;
    tried: boolean;
    resultsLength: number;
    versionNotFound: boolean;
    bibleGatewayUrl: string | null;
    ogPreview: { title?: string; description?: string; image?: string } | null;
    ogLoading: boolean;
    ogError: string | null;
  }

  let { 
    query, 
    bookType, 
    parsedQuery, 
    tried, 
    resultsLength, 
    versionNotFound,
    bibleGatewayUrl,
    ogPreview,
    ogLoading,
    ogError
  }: Props = $props();

  const bookTypeDisplayName = BOOK_TYPES[bookType]?.displayName || bookType.charAt(0).toUpperCase() + bookType.slice(1);
</script>

{#if tried && resultsLength === 0 && !versionNotFound}
  <div class="mt-4 space-y-4">
    <div class="text-gray-500 italic">
      No {bookTypeDisplayName.toLowerCase()} passages found for "{query}"
    </div>
    {#if bookType === 'bible'}
      <div class="bg-white border border-gray-200 rounded-lg p-4 shadow-sm">
        <div class="text-xs text-gray-400 italic mb-3 leading-relaxed">
          The search result was not found on the relays. Here is the result from a different website:
        </div>
        {#if ogLoading}
          <div class="flex items-center gap-2 text-xs text-gray-500">
            <div class="book-og-spinner"></div>
            <span>Loading preview from BibleGateway...</span>
          </div>
        {:else if ogPreview}
          <div class="space-y-3">
            <div class="space-y-2">
              <div class="flex items-center gap-2">
                <h3 class="text-base font-bold text-gray-900">BibleGateway</h3>
              </div>
              <div class="font-semibold text-sm text-gray-800">
                {ogPreview.title || 'Bible passage'}
              </div>
            </div>
            <div class="text-sm text-gray-700 leading-relaxed">
              {ogPreview.description || 'Preview generated by BibleGateway'}
            </div>
            {#if ogPreview.image && bibleGatewayUrl}
              <div class="flex justify-center">
                <a
                  href={bibleGatewayUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  class="block transition-opacity hover:opacity-80"
                >
                  <img
                    src={ogPreview.image}
                    alt={ogPreview.title || 'BibleGateway preview'}
                    class="max-w-xs h-20 object-contain opacity-60"
                  />
                </a>
              </div>
            {/if}
          </div>
        {:else if ogError}
          <div class="text-xs text-rose-500">{ogError}</div>
        {:else if !bibleGatewayUrl}
          <div class="text-xs text-amber-600">Could not generate BibleGateway URL. Query: "{query}"</div>
        {:else}
          <div class="text-xs text-gray-500">Preview unavailable.</div>
        {/if}
      </div>
    {/if}
  </div>
{:else if versionNotFound && resultsLength === 0}
  <div class="mt-4 space-y-4">
    <div class="bg-yellow-50 border border-yellow-200 rounded-lg p-4">
      <div class="flex items-center space-x-2 text-yellow-800">
        <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
          <path fill-rule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clip-rule="evenodd"></path>
        </svg>
        <span class="font-medium">Version not found</span>
      </div>
      <div class="mt-2 text-sm text-yellow-700">
        The requested version "{parsedQuery?.version || parsedQuery?.versions?.[0]}" was not found. Showing the BibleGateway preview while passages load.
      </div>
    </div>
    <div class="text-gray-500 italic">
      Searching for all versions of "{query.replace(/\s*\|\s*[^|]+\s*$/, '')}"...
    </div>
    {#if bookType === 'bible'}
      <div class="bg-white border border-gray-200 rounded-lg p-4 shadow-sm">
        <div class="text-xs text-gray-400 italic mb-3 leading-relaxed">
          The search result was not found on the relays. Here is the result from a different website:
        </div>
        {#if ogLoading}
          <div class="flex items-center gap-2 text-xs text-gray-500">
            <div class="book-og-spinner"></div>
            <span>Loading preview from BibleGateway...</span>
          </div>
        {:else if ogPreview}
          <div class="space-y-3">
            <div class="space-y-2">
              <div class="flex items-center gap-2">
                <h3 class="text-base font-bold text-gray-900">BibleGateway</h3>
              </div>
              <div class="font-semibold text-sm text-gray-800">
                {ogPreview.title || 'Bible passage'}
              </div>
            </div>
            <div class="text-sm text-gray-700 leading-relaxed">
              {ogPreview.description || 'Preview generated by BibleGateway'}
            </div>
            {#if ogPreview.image && bibleGatewayUrl}
              <div class="flex justify-center">
                <a
                  href={bibleGatewayUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  class="block transition-opacity hover:opacity-80"
                >
                  <img
                    src={ogPreview.image}
                    alt={ogPreview.title || 'BibleGateway preview'}
                    class="max-w-xs h-20 object-contain opacity-60"
                  />
                </a>
              </div>
            {/if}
          </div>
        {:else if ogError}
          <div class="text-xs text-rose-500">{ogError}</div>
        {:else if !bibleGatewayUrl}
          <div class="text-xs text-amber-600">Could not generate BibleGateway URL. Query: "{query}"</div>
        {:else}
          <div class="text-xs text-gray-500">Preview unavailable.</div>
        {/if}
      </div>
    {/if}
  </div>
{/if}

<style>
  .book-og-spinner {
    width: 14px;
    height: 14px;
    border: 2px solid var(--border);
    border-top-color: var(--accent);
    border-radius: 9999px;
    animation: spin 1s linear infinite;
  }

  @keyframes spin {
    0% {
      transform: rotate(0deg);
    }
    100% {
      transform: rotate(360deg);
    }
  }
</style>