<script lang="ts">
  import type { BookReference } from '$lib/books';
  import { generateBibleGatewayUrlForReference } from '$lib/bibleGatewayUtils';
  import { formatSections } from '$lib/utils';

  interface Props {
    parsedQuery: { references: BookReference[]; version?: string; versions?: string[] } | null;
    bibleGatewayUrl: string | null;
    referenceOgPreviews: Map<string, { title?: string; description?: string; image?: string } | null>;
    referenceOgLoading: Map<string, boolean>;
    referenceOgErrors: Map<string, string | null>;
    // Helper functions for getting reference keys
    getReferenceKey: (ref: BookReference) => string;
    getReferenceKeyWithVersion?: (ref: BookReference, version?: string) => string;
    // Optional: version for version-specific cards
    version?: string;
    // Optional: version display name
    versionDisplayName?: string;
    // Optional: if true, don't wrap in version card container (for use inside existing version cards)
    noWrapper?: boolean;
  }

  let {
    parsedQuery,
    bibleGatewayUrl,
    referenceOgPreviews,
    referenceOgLoading,
    referenceOgErrors,
    getReferenceKey,
    getReferenceKeyWithVersion,
    version,
    versionDisplayName,
    noWrapper = false
  }: Props = $props();

  function getRefKey(ref: BookReference): string {
    if (version && getReferenceKeyWithVersion) {
      return getReferenceKeyWithVersion(ref, version);
    }
    return getReferenceKey(ref);
  }

  function getRefVersion(ref: BookReference): string | undefined {
    return version || parsedQuery?.versions?.[0] || parsedQuery?.version;
  }

  function formatReference(ref: BookReference): string {
    const parts: string[] = [];
    if (ref.book) parts.push(ref.book);
    if (ref.chapter) parts.push(String(ref.chapter));
    if (ref.verse) {
      const verseParts = ref.verse.includes(',') ? ref.verse.split(',').map(v => v.trim()) : [ref.verse];
      parts.push(formatSections(verseParts));
    }
    return parts.join(' ');
  }

  // Determine version display name
  const displayVersionName = $derived(
    versionDisplayName || version?.toUpperCase() || parsedQuery?.versions?.[0]?.toUpperCase() || parsedQuery?.version?.toUpperCase() || ''
  );

  // Get button OG image from first reference's preview
  const buttonOgImage = $derived(
    parsedQuery?.references?.[0] 
      ? referenceOgPreviews.get(getRefKey(parsedQuery.references[0]))?.image 
      : null
  );
</script>

{#if parsedQuery && parsedQuery.references.length > 0}
  {#if noWrapper}
    <!-- No wrapper - content only (for use inside existing version cards) -->
    <!-- Informational message -->
    <div class="text-xs text-gray-400 italic leading-relaxed" style="margin-bottom: 1rem;">
      The search result was not found on the relays. Here is the result from a different website:
    </div>

    <!-- Reference previews -->
    <div class="space-y-4">
      {#each parsedQuery.references as ref}
        {@const refKey = getRefKey(ref)}
        {@const refBgUrl = generateBibleGatewayUrlForReference(ref, getRefVersion(ref))}
        {@const refPreview = referenceOgPreviews.get(refKey) || null}
        {@const refLoading = referenceOgLoading.get(refKey) || false}
        {@const refError = referenceOgErrors.get(refKey) || null}
        {@const hasAttemptedLoad = referenceOgPreviews.has(refKey) || referenceOgErrors.has(refKey) || referenceOgLoading.has(refKey)}
        
        <!-- Bible Gateway passage card -->
        <div class="bg-white border border-gray-200 rounded-lg p-4 shadow-sm">
          {#if refLoading || (!hasAttemptedLoad && refBgUrl && !refPreview && !refError)}
            <!-- Show loading if actively loading OR if we haven't attempted yet (URL exists but no load attempted) -->
            <div class="flex items-center gap-2 text-xs text-gray-500">
              <div class="book-og-spinner"></div>
              <span>Loading preview from BibleGateway...</span>
            </div>
          {:else if refPreview}
            <div class="space-y-3">
              <div class="space-y-1">
                <div class="font-semibold text-sm text-gray-800">
                  {refPreview.title || formatReference(ref)}
                </div>
              </div>
              <div class="text-sm text-gray-700 leading-relaxed">
                {refPreview.description || 'Preview generated by BibleGateway'}
              </div>
            </div>
          {:else if refError}
            <div class="text-xs text-rose-500">{refError}</div>
          {:else if !refBgUrl}
            <div class="text-xs text-amber-600">Could not generate BibleGateway URL for {formatReference(ref)}</div>
          {:else}
            <!-- Only show unavailable if we've tried and failed (no preview, no error, no URL) -->
            <div class="text-xs text-gray-500">Preview unavailable for {formatReference(ref)}.</div>
          {/if}
        </div>
      {/each}

      <!-- View All Passages button -->
      {#if bibleGatewayUrl}
        <div class="flex justify-center pt-2">
          <a
            href={bibleGatewayUrl}
            target="_blank"
            rel="noopener noreferrer"
            class="inline-flex items-center gap-2 px-4 py-2 bg-gray-200 text-gray-700 rounded-lg font-semibold hover:bg-gray-300 transition-colors shadow-sm hover:shadow"
          >
            {#if buttonOgImage}
              <img
                src={buttonOgImage}
                alt="BibleGateway"
                class="w-10 h-10 object-contain"
                onerror={(e) => {
                  const img = e.currentTarget as HTMLImageElement;
                  img.style.display = 'none';
                  const svg = img.nextElementSibling as HTMLElement;
                  if (svg) svg.classList.remove('hidden');
                }}
              />
            {/if}
            <svg class="w-10 h-10 {buttonOgImage ? 'hidden' : ''}" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" />
            </svg>
            View All Passages on BibleGateway
          </a>
        </div>
      {/if}
    </div>
  {:else}
    <!-- Version card style container with purple border -->
    <div 
      class="version-group" 
      style="margin: 2rem 0; border: 2px solid var(--accent); border-radius: 0.75rem; padding: 1.5rem; background-color: var(--bg-primary); position: relative;"
    >
      <!-- Version Header (if version specified) -->
      {#if displayVersionName}
        <div 
          class="version-header" 
          style="font-size: 0.75em; font-variant: small-caps; letter-spacing: 0.1em; margin-bottom: 1rem; color: var(--text-secondary, #6b7280); opacity: 0.8; padding-bottom: 0.5rem; border-bottom: 1px solid var(--border, #e5e7eb);"
        >
          {displayVersionName}
        </div>
      {/if}

      <!-- Informational message -->
      <div class="text-xs text-gray-400 italic leading-relaxed" style="margin-bottom: 1rem;">
        The search result was not found on the relays. Here is the result from a different website:
      </div>

      <!-- Reference previews -->
      <div class="space-y-4">
        {#each parsedQuery.references as ref}
          {@const refKey = getRefKey(ref)}
          {@const refBgUrl = generateBibleGatewayUrlForReference(ref, getRefVersion(ref))}
          {@const refPreview = referenceOgPreviews.get(refKey) || null}
          {@const refLoading = referenceOgLoading.get(refKey) || false}
          {@const refError = referenceOgErrors.get(refKey) || null}
          {@const hasAttemptedLoad = referenceOgPreviews.has(refKey) || referenceOgErrors.has(refKey) || referenceOgLoading.has(refKey)}
          
          <!-- Bible Gateway passage card -->
          <div class="bg-white border border-gray-200 rounded-lg p-4 shadow-sm">
            {#if refLoading || (!hasAttemptedLoad && refBgUrl && !refPreview && !refError)}
              <!-- Show loading if actively loading OR if we haven't attempted yet (URL exists but no load attempted) -->
              <div class="flex items-center gap-2 text-xs text-gray-500">
                <div class="book-og-spinner"></div>
                <span>Loading preview from BibleGateway...</span>
              </div>
            {:else if refPreview}
              <div class="space-y-3">
                <div class="space-y-1">
                  <div class="font-semibold text-sm text-gray-800">
                    {refPreview.title || formatReference(ref)}
                  </div>
                </div>
                <div class="text-sm text-gray-700 leading-relaxed">
                  {refPreview.description || 'Preview generated by BibleGateway'}
                </div>
              </div>
            {:else if refError}
              <div class="text-xs text-rose-500">{refError}</div>
            {:else if !refBgUrl}
              <div class="text-xs text-amber-600">Could not generate BibleGateway URL for {formatReference(ref)}</div>
            {:else}
              <!-- Only show unavailable if we've tried and failed (no preview, no error, no URL) -->
              <div class="text-xs text-gray-500">Preview unavailable for {formatReference(ref)}.</div>
            {/if}
          </div>
        {/each}

        <!-- View All Passages button -->
        {#if bibleGatewayUrl}
          <div class="flex justify-center pt-2">
            <a
              href={bibleGatewayUrl}
              target="_blank"
              rel="noopener noreferrer"
              class="inline-flex items-center gap-2 px-4 py-2 bg-gray-200 text-gray-700 rounded-lg font-semibold hover:bg-gray-300 transition-colors shadow-sm hover:shadow"
            >
              {#if buttonOgImage}
                <img
                  src={buttonOgImage}
                  alt="BibleGateway"
                  class="w-10 h-10 object-contain"
                  onerror={(e) => {
                    const img = e.currentTarget as HTMLImageElement;
                    img.style.display = 'none';
                    const svg = img.nextElementSibling as HTMLElement;
                    if (svg) svg.classList.remove('hidden');
                  }}
                />
              {/if}
              <svg class="w-10 h-10 {buttonOgImage ? 'hidden' : ''}" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" />
              </svg>
              View All Passages on BibleGateway
            </a>
          </div>
        {/if}
      </div>
    </div>
  {/if}
{/if}

<style>
  .book-og-spinner {
    width: 14px;
    height: 14px;
    border: 2px solid var(--border);
    border-top-color: var(--accent);
    border-radius: 9999px;
    animation: spin 1s linear infinite;
  }

  @keyframes spin {
    0% {
      transform: rotate(0deg);
    }
    100% {
      transform: rotate(360deg);
    }
  }
</style>

