<script lang="ts">
  import type { BookReference } from '$lib/books';
  import { formatSections } from '$lib/utils';

  interface Props {
    reference: BookReference;
    bibleGatewayUrl: string | null;
    ogPreview: { title?: string; description?: string; image?: string } | null;
    ogLoading: boolean;
    ogError: string | null;
  }

  let { 
    reference,
    bibleGatewayUrl,
    ogPreview,
    ogLoading,
    ogError
  }: Props = $props();

  // Helper to format reference for display
  function formatReference(ref: BookReference): string {
    const parts: string[] = [];
    if (ref.book) parts.push(ref.book);
    if (ref.chapter) parts.push(String(ref.chapter));
    if (ref.verse) {
      // If verse is comma-separated (e.g., "16,17,18"), format it as a range
      const verseParts = ref.verse.includes(',') ? ref.verse.split(',').map(v => v.trim()) : [ref.verse];
      parts.push(formatSections(verseParts));
    }
    return parts.join(' ');
  }
</script>

<div class="bg-white border border-gray-200 rounded-lg p-4 shadow-sm">
  {#if ogLoading}
    <div class="flex items-center gap-2 text-xs text-gray-500">
      <div class="book-og-spinner"></div>
      <span>Loading preview from BibleGateway...</span>
    </div>
  {:else if ogPreview}
    <div class="space-y-3">
      <div class="space-y-1">
        <div class="font-semibold text-sm text-gray-800">
          {ogPreview.title || formatReference(reference)}
        </div>
      </div>
      <div class="text-sm text-gray-700 leading-relaxed">
        {ogPreview.description || 'Preview generated by BibleGateway'}
      </div>
    </div>
  {:else if ogError}
    <div class="text-xs text-rose-500">{ogError}</div>
  {:else if !bibleGatewayUrl}
    <div class="text-xs text-amber-600">Could not generate BibleGateway URL for {formatReference(reference)}</div>
  {:else}
    <div class="text-xs text-gray-500">Preview unavailable for {formatReference(reference)}.</div>
  {/if}
</div>

<style>
  .book-og-spinner {
    width: 14px;
    height: 14px;
    border: 2px solid var(--border);
    border-top-color: var(--accent);
    border-radius: 9999px;
    animation: spin 1s linear infinite;
  }

  @keyframes spin {
    0% {
      transform: rotate(0deg);
    }
    100% {
      transform: rotate(360deg);
    }
  }
</style>
